// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaS2V19mjy3JamNQBCS_-adTZLPrQDnmI',
    appId: '1:698580119472:web:577dff151f498b1ebbb075',
    messagingSenderId: '698580119472',
    projectId: 'qalaska-50ad9',
    authDomain: 'qalaska-50ad9.firebaseapp.com',
    storageBucket: 'qalaska-50ad9.appspot.com',
    measurementId: 'G-MF2ZCWKP5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCekci_rsNJOaiGI1O1CCrpq_rVAMZ1YI',
    appId: '1:698580119472:android:26449f4f76bd5d53bbb075',
    messagingSenderId: '698580119472',
    projectId: 'qalaska-50ad9',
    storageBucket: 'qalaska-50ad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhWftVIOBq98zT-RY6xEGKK3erLXzZV4',
    appId: '1:698580119472:ios:043036f69b75371cbbb075',
    messagingSenderId: '698580119472',
    projectId: 'qalaska-50ad9',
    storageBucket: 'qalaska-50ad9.appspot.com',
    iosBundleId: 'com.example.dice2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaS2V19mjy3JamNQBCS_-adTZLPrQDnmI',
    appId: '1:698580119472:web:5d4e617c4576f25cbbb075',
    messagingSenderId: '698580119472',
    projectId: 'qalaska-50ad9',
    authDomain: 'qalaska-50ad9.firebaseapp.com',
    storageBucket: 'qalaska-50ad9.appspot.com',
    measurementId: 'G-GJHQ5R7SJM',
  );
}
